<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/AccessCity.Core/AccessCity.Core.csproj" />
    <ProjectReference Include="../../src/AccessCity.Infrastructure/AccessCity.Infrastructure.csproj" />
    <ProjectReference Include="../../src/AccessCity.DataProviders/AccessCity.DataProviders.csproj" />
  </ItemGroup>
</Project>
